export interface ExhibitionArtwork {
  id: string;
  chamberId: string;
  title: string;
  project: string;
  location: string;
  category: string;
  image: string;
  description: string;
  materials: string[];
  dimensions: string;
  aspectRatio: "landscape" | "portrait" | "panoramic";
}

export const EXHIBITION_CATALOG: Record<string, ExhibitionArtwork[]> = {
  grand: [
    {
      id: "ch1_living",
      chamberId: "grand",
      title: "The Monolithic Living Suite",
      project: "Koregaon Park Estate",
      location: "Pune, Maharashtra",
      category: "Double-Height Main Salon",
      image: "/assets/exhibition/ch1_living.jpg",
      description:
        "A sprawling double-height living salon anchored by book-matched Italian Statuario marble slabs with subtle champagne gold veining. Bespoke low-profile modular seating in textured Belgian taupe linen wraps the central lounge, complemented by floating monolithic tables in honed Nero Marquina and brushed brass accents.",
      materials: ["Statuario Gold Marble", "Belgian Taupe Linen", "Honed Nero Marquina", "Brushed Brass Reveal"],
      dimensions: "12.2m × 5.8m Monumental Display",
      aspectRatio: "panoramic",
    },
    {
      id: "ch1_dining",
      chamberId: "grand",
      title: "The Grand Stone Salon",
      project: "Koregaon Park Estate",
      location: "Pune, Maharashtra",
      category: "Formal Living Salon",
      image: "/assets/exhibition/ch1_dining.jpg",
      description:
        "A grand formal living chamber featuring natural rustic stone wall cladding, coffered warm timber ceiling beams, tailored low-slung leather sofa seating, and round sculptural coffee tables bathed in generous natural daylight from garden glass fenestrations.",
      materials: ["Chiseled Natural Stone", "Smoked Walnut Beams", "Cognac Saddle Leather", "Architectural Downlights"],
      dimensions: "5.8m × 3.8m Wall Frame",
      aspectRatio: "landscape",
    },
    {
      id: "ch1_parlour",
      chamberId: "grand",
      title: "The Double-Height Main Salon",
      project: "Koregaon Park Estate",
      location: "Pune, Maharashtra",
      category: "Grand Reception Hall",
      image: "/assets/exhibition/ch1_parlour.jpg",
      description:
        "Panoramic perspective of the grand living hall showcasing monumental ceiling heights, contemporary multi-tiered crystal chandeliers, designer Italian leather sofas, and continuous floor-to-ceiling architectural drapery.",
      materials: ["Crystal Chandelier", "Book-matched Marble Floor", "Custom Tufted Seating", "Warm Perimeter LED Coving"],
      dimensions: "5.8m × 3.8m Wall Frame",
      aspectRatio: "landscape",
    },
    {
      id: "ch1_lounge",
      chamberId: "grand",
      title: "The Horizon Leather Lounge",
      project: "Koregaon Park Estate",
      location: "Pune, Maharashtra",
      category: "Modular Living Lounge",
      image: "/assets/exhibition/ch1_lounge.jpg",
      description:
        "An expansive modern living lounge with bespoke modular sectionals, floating stone coffee tables, geometric ceiling coffer trays, and an acoustic timber slat wall that balances grand scale with intimate conversation comfort.",
      materials: ["Modular Saddle Leather", "Geometric Coffer Trays", "Black Travertine Tables", "Acoustic Timber Slats"],
      dimensions: "5.8m × 3.8m Wall Frame",
      aspectRatio: "landscape",
    },
    {
      id: "ch1_media",
      chamberId: "grand",
      title: "The Modern Entertainment Salon",
      project: "Koregaon Park Estate",
      location: "Pune, Maharashtra",
      category: "Living & AV Salon",
      image: "/assets/exhibition/ch1_media.jpg",
      description:
        "A sophisticated living entertainment salon featuring sliding black-framed glass acoustics, integrated warm ceiling cove illumination, and bespoke sectional seating designed for serene family relaxation.",
      materials: ["Acoustic Glass Partitions", "Warm Amber Coving", "Bespoke Fabric Sectional", "Engineered Hardwood Floor"],
      dimensions: "5.8m × 3.8m Wall Frame",
      aspectRatio: "landscape",
    },
  ],

  versace: [
    {
      id: "ch2_woodbed",
      chamberId: "versace",
      title: "The Signature Versace Suite",
      project: "Worli Sea Face Residence",
      location: "Mumbai, Maharashtra",
      category: "Master Bedroom Chamber",
      image: "/assets/exhibition/ch2_woodbed.jpg",
      description:
        "The centerpiece master bedroom suite showcasing a bespoke burgundy aniline leather headboard, embroidered Versace silk accents, vertical fluted European white oak wall paneling, and dual minimalist brass pendant sconces providing intimate reading illumination.",
      materials: ["Burgundy Aniline Leather", "Versace Embroidered Silk", "Fluted White Oak Paneling", "Brushed Brass Sconces"],
      dimensions: "12.2m × 5.8m Monumental Display",
      aspectRatio: "panoramic",
    },
    {
      id: "ch2_bed1",
      chamberId: "versace",
      title: "The Versace Crest Atelier",
      project: "Worli Sea Face Residence",
      location: "Mumbai, Maharashtra",
      category: "Master Suite Detail",
      image: "/assets/exhibition/ch2_bed1.jpg",
      description:
        "Intimate composition highlighting the exquisite Versace embroidered crest pillow, plush cushioned headboard upholstery, polished burl veneer wall finish, and flush shadow gap joinery detailing.",
      materials: ["Versace Gold Crest Pillow", "High-Gloss Burl Veneer", "Custom Bedside Inductive Charging", "Matte Bronze Trim"],
      dimensions: "5.8m × 3.8m Wall Frame",
      aspectRatio: "landscape",
    },
    {
      id: "ch2_vanity",
      chamberId: "versace",
      title: "The Fluted Channel Master Chamber",
      project: "Worli Sea Face Residence",
      location: "Mumbai, Maharashtra",
      category: "Master Suite Chamber",
      image: "/assets/exhibition/ch2_vanity.jpg",
      description:
        "A tranquil master sanctuary featuring full-height vertical channel-tufted upholstered wall panels in warm oatmeal bouclé, integrated indirect 2700K perimeter cove lighting, and ceiling-recessed sheer drapery tracks.",
      materials: ["Channel-Tufted Bouclé", "Concealed Warm Coving", "Full-Height Sheer Drapery", "Nero Marquina Side Tables"],
      dimensions: "5.8m × 3.8m Wall Frame",
      aspectRatio: "landscape",
    },
    {
      id: "ch2_emerald",
      chamberId: "versace",
      title: "The Modern Noir Master Suite",
      project: "Worli Sea Face Residence",
      location: "Mumbai, Maharashtra",
      category: "Contemporary Master Suite",
      image: "/assets/exhibition/ch2_emerald.jpg",
      description:
        "Dramatic contemporary master suite with a deep charcoal velvet upholstered headboard, vertical natural wood wall slats, suspended spherical blown glass pendants, and subtle warm backlighting.",
      materials: ["Charcoal Belgian Velvet", "Vertical Wood Slats", "Artisan Blown Glass Pendants", "Smoked Oak Hardwood"],
      dimensions: "5.8m × 3.8m Wall Frame",
      aspectRatio: "landscape",
    },
    {
      id: "ch2_linear",
      chamberId: "versace",
      title: "The Amber Wood Grain Suite",
      project: "Worli Sea Face Residence",
      location: "Mumbai, Maharashtra",
      category: "Warm Timber Master Chamber",
      image: "/assets/exhibition/ch2_linear.jpg",
      description:
        "An opulent bedroom chamber wrapped in book-matched amber wood veneer wall paneling with a floating king platform bed, cantilevered bedside pedestals, and designer task lamps.",
      materials: ["Book-matched Amber Timber", "Cantilevered Bedside Tables", "Brushed Brass Inlays", "Circadian Accent Lighting"],
      dimensions: "5.8m × 3.8m Wall Frame",
      aspectRatio: "landscape",
    },
  ],

  sacred: [
    {
      id: "ch3_mandir_classic",
      chamberId: "sacred",
      title: "The Divine Venkateswara Sanctum",
      project: "Amanora Park Town Sanctuary",
      location: "Pune, Maharashtra",
      category: "Sacred Mandir Chamber",
      image: "/assets/exhibition/ch3_mandir_classic.jpg",
      description:
        "A monumental puja altar centered on an illuminated circular halo of Lord Tirupati Venkateswara, framed by a laser-etched Sanskrit Gayatri Mantra feature wall, Om iconographic engravings, and bespoke fluted coral red deity storage cabinetry.",
      materials: ["Backlit Venkateswara Halo", "Laser-Etched Gayatri Wall", "Fluted Coral Deity Credenza", "Solid Cast Brass Bells"],
      dimensions: "12.2m × 5.8m Monumental Display",
      aspectRatio: "panoramic",
    },
    {
      id: "ch3_stone_altar",
      chamberId: "sacred",
      title: "The Sacred Altar & Temple Bells",
      project: "Amanora Park Town Sanctuary",
      location: "Pune, Maharashtra",
      category: "Spiritual Puja Mandir",
      image: "/assets/exhibition/ch3_stone_altar.jpg",
      description:
        "Sprawling frontal view of the sacred altar displaying handcrafted solid brass temple bells suspended from link chains, polished brass diya holders, and authentic brass deity idols resting upon the carved ceremonial altar table.",
      materials: ["Solid Brass Temple Bells", "Carved Coral Wood Altar", "Cast Brass Idols", "Architectural Accent Downlights"],
      dimensions: "5.8m × 3.8m Wall Frame",
      aspectRatio: "landscape",
    },
    {
      id: "ch3_courtyard",
      chamberId: "sacred",
      title: "The Deity Sanctum Pavilion",
      project: "Amanora Park Town Sanctuary",
      location: "Pune, Maharashtra",
      category: "Puja Idol Sanctuary",
      image: "/assets/exhibition/ch3_courtyard.jpg",
      description:
        "Intimate composition of the sacred sanctum showcasing consecrated brass deities surrounded by traditional puja accessories, fragrant marigold offerings, and indirect amber ambient backlighting.",
      materials: ["Consecrated Brass Idols", "Antique Brass Diya Lamps", "Polished Ivory Stone Base", "2400K Amber Illumination"],
      dimensions: "5.8m × 3.8m Wall Frame",
      aspectRatio: "landscape",
    },
    {
      id: "ch3_foyer",
      chamberId: "sacred",
      title: "The Heritage Teakwood Mandir",
      project: "Amanora Park Town Sanctuary",
      location: "Pune, Maharashtra",
      category: "Traditional Temple Mandir",
      image: "/assets/exhibition/ch3_foyer.jpg",
      description:
        "A magnificent full-height traditional Indian temple mandir handcrafted in Burmese teakwood. Features exquisite floral jali door panels with hanging brass bells, an illuminated radiant mandala ceiling, and a sacred marble sanctum.",
      materials: ["Burmese Teakwood", "Floral Jali Door Panels", "Radiant Mandala Ceiling", "White Statuario Base"],
      dimensions: "5.8m × 3.8m Wall Frame",
      aspectRatio: "landscape",
    },
    {
      id: "ch3_portal",
      chamberId: "sacred",
      title: "The Symmetrical Jali Sanctum",
      project: "Amanora Park Town Sanctuary",
      location: "Pune, Maharashtra",
      category: "Temple Jali Sanctum",
      image: "/assets/exhibition/ch3_portal.jpg",
      description:
        "Symmetrical architectural study of the handcrafted teakwood mandir doors, showcasing precision geometric fretwork, rhythmic brass bell integration, and sacred proportions designed for spiritual peace.",
      materials: ["Handcrafted Teakwood Jali", "Hanging Temple Bells", "Warm Inner Sanctum Wash", "Checkerboard Marble Floor"],
      dimensions: "5.8m × 3.8m Wall Frame",
      aspectRatio: "landscape",
    },
  ],

  corporate: [
    {
      id: "ch4_boardroom",
      chamberId: "corporate",
      title: "The Presidential Boardroom",
      project: "BKC Commercial Hub",
      location: "Mumbai, Maharashtra",
      category: "Executive Boardroom",
      image: "/assets/exhibition/ch4_boardroom.jpg",
      description:
        "A monumental executive boardroom centered around a custom conference table with ergonomic high-back executive leather armchairs, rich book-matched walnut wall paneling, and an integrated ceiling lighting grid with flush linear diffusers.",
      materials: ["Book-matched Walnut Paneling", "Ergonomic Executive Leather", "Linear Track Lighting Grid", "Acoustic Glass Partitions"],
      dimensions: "12.2m × 5.8m Monumental Display",
      aspectRatio: "panoramic",
    },
    {
      id: "ch4_skylounge",
      chamberId: "corporate",
      title: "The Managing Director Cabin",
      project: "BKC Commercial Hub",
      location: "Mumbai, Maharashtra",
      category: "Managing Director Suite",
      image: "/assets/exhibition/ch4_skylounge.jpg",
      description:
        "The private executive suite of the Managing Director, featuring a monolithic modern executive desk, cognac leather executive chair, contemporary cobalt blue wall artwork, and visitor seating lounge.",
      materials: ["Monolithic Executive Desk", "Cognac Saddle Leather", "Curated Blue Fine Art Panels", "Concealed Cable Management"],
      dimensions: "5.8m × 3.8m Wall Frame",
      aspectRatio: "landscape",
    },
    {
      id: "ch4_dining",
      chamberId: "corporate",
      title: "The Executive Conference Suite",
      project: "BKC Commercial Hub",
      location: "Mumbai, Maharashtra",
      category: "Executive Conference Chamber",
      image: "/assets/exhibition/ch4_dining.jpg",
      description:
        "Full conference room perspective showcasing the presentation feature wall clad in rich burled timber, bronze framed shelving, and executive seating tailored for high-level board meetings.",
      materials: ["Burled Walnut Feature Wall", "Bronze Trimmed Display Vitrines", "Matte Conference Top", "High-Back Leather Chairs"],
      dimensions: "5.8m × 3.8m Wall Frame",
      aspectRatio: "landscape",
    },
    {
      id: "ch4_vip",
      chamberId: "corporate",
      title: "The Laxmi Corporate Reception",
      project: "BKC Commercial Hub",
      location: "Mumbai, Maharashtra",
      category: "Corporate Reception & Foyer",
      image: "/assets/exhibition/ch4_vip.jpg",
      description:
        "The commanding corporate entrance foyer featuring a custom brass and fluted wood reception desk, illuminated corporate insignia, eggplant velvet lounge seating, and geometric marble flooring.",
      materials: ["Bespoke Brass Reception Desk", "Illuminated Insignia Wall", "Eggplant Velvet Armchairs", "Polished Italian Marble Floor"],
      dimensions: "5.8m × 3.8m Wall Frame",
      aspectRatio: "landscape",
    },
    {
      id: "ch4_terrace",
      chamberId: "corporate",
      title: "The Director Private Office",
      project: "BKC Commercial Hub",
      location: "Mumbai, Maharashtra",
      category: "Private Executive Office",
      image: "/assets/exhibition/ch4_terrace.jpg",
      description:
        "A private director office suite boasting a custom slatted timber ceiling tray, floating executive desk, integrated trophy credenza, and motorized acoustic window louvers.",
      materials: ["Slatted Timber Ceiling", "Floating Executive Desk", "Custom Trophy Credenza", "Acoustic Window Louvers"],
      dimensions: "5.8m × 3.8m Wall Frame",
      aspectRatio: "landscape",
    },
  ],

  royal_living: [
    {
      id: "ch5_living",
      chamberId: "royal_living",
      title: "The Royal Media & Living Salon",
      project: "Koregaon Park Estate",
      location: "Pune, Maharashtra",
      category: "Double-Height Living Salon",
      image: "/assets/exhibition/ch5_living.jpg",
      description:
        "An expansive living salon centered on a bespoke backlit marble media wall with warm vertical timber millwork, tailored cream leather sectionals, floating tiered coffee tables, and layered cove illumination.",
      materials: ["Backlit Italian Marble", "Vertical Timber Millwork", "Cream Italian Leather", "Layered Cove Illumination"],
      dimensions: "12.2m × 5.8m Monumental Display",
      aspectRatio: "panoramic",
    },
    {
      id: "ch5_lounge",
      chamberId: "royal_living",
      title: "The Bespoke Leather Conversation Lounge",
      project: "Koregaon Park Estate",
      location: "Pune, Maharashtra",
      category: "Executive Living Lounge",
      image: "/assets/exhibition/ch5_lounge.jpg",
      description:
        "An intimate living lounge designed for deep conversation, featuring plush low-profile leather armchairs, a chiseled stone coffee table, and ceiling-recessed linen drapery filtering soft diffuse daylight.",
      materials: ["Supple Italian Leather", "Chiseled Stone Coffee Table", "Recessed Linen Drapery", "Minimalist Wall Sconces"],
      dimensions: "5.8m × 3.8m Wall Frame",
      aspectRatio: "landscape",
    },
    {
      id: "ch5_staircase",
      chamberId: "royal_living",
      title: "The Floating Staircase Architectural Salon",
      project: "Koregaon Park Estate",
      location: "Pune, Maharashtra",
      category: "Architectural Living Hall",
      image: "/assets/exhibition/ch5_staircase.jpg",
      description:
        "Dramatic living hall perspective showcasing a cantilevered floating staircase with concealed riser LEDs, double-height sheer drapery, and tailored modular seating nestled beneath.",
      materials: ["Cantilevered Floating Steps", "Concealed Warm Step LEDs", "Double-Height Sheer Curtains", "Smoked Oak Detailing"],
      dimensions: "5.8m × 3.8m Wall Frame",
      aspectRatio: "landscape",
    },
    {
      id: "ch5_minimalist",
      chamberId: "royal_living",
      title: "The Contemporary Minimalist Living Pavilion",
      project: "Koregaon Park Estate",
      location: "Pune, Maharashtra",
      category: "Minimalist Living Room",
      image: "/assets/exhibition/ch5_minimalist.jpg",
      description:
        "Sprawling living room composition with low-profile cream modular sofas, glass-topped architectural cocktail tables, botanical planters, and continuous Statuario marble flooring.",
      materials: ["Low-Profile Modular Sofas", "Architectural Glass Cocktail Table", "White Statuario Marble", "Fluted Wall Finishes"],
      dimensions: "5.8m × 3.8m Wall Frame",
      aspectRatio: "landscape",
    },
    {
      id: "ch5_velvet",
      chamberId: "royal_living",
      title: "The Jewel-Tone Velvet Living Suite",
      project: "Koregaon Park Estate",
      location: "Pune, Maharashtra",
      category: "Bespoke Formal Living",
      image: "/assets/exhibition/ch5_velvet.jpg",
      description:
        "An opulent formal salon wrapped in natural wood paneling with jewel-toned emerald and ruby velvet sofas, circular stone ottomans, and recessed perimeter illumination.",
      materials: ["Emerald Belgian Velvet", "Ruby Leather Armchairs", "Natural Wood Wall Cladding", "Round Marble Ottomans"],
      dimensions: "5.8m × 3.8m Wall Frame",
      aspectRatio: "landscape",
    },
  ],

  corporate_lobby: [
    {
      id: "ch6_reception",
      chamberId: "corporate_lobby",
      title: "The Laxmi Commercial Reception Desk",
      project: "BKC Commercial Hub",
      location: "Mumbai, Maharashtra",
      category: "Corporate Reception & Concierge",
      image: "/assets/exhibition/ch6_reception.jpg",
      description:
        "A commanding commercial reception area highlighted by a sculptural brushed brass concierge desk, illuminated backlit corporate insignia, chevron wood wall accents, and custom fluted glass conference portals.",
      materials: ["Brushed Brass Concierge Counter", "Illuminated Chevron Wood Wall", "Fluted Glass Partitions", "Polished Marble Floor"],
      dimensions: "12.2m × 5.8m Monumental Display",
      aspectRatio: "panoramic",
    },
    {
      id: "ch6_chevron",
      chamberId: "corporate_lobby",
      title: "The Sculptural Chevron Reception Counter",
      project: "BKC Commercial Hub",
      location: "Mumbai, Maharashtra",
      category: "Reception Counter Detail",
      image: "/assets/exhibition/ch6_chevron.jpg",
      description:
        "Frontal architectural focus on the handcrafted chevron timber paneling, laser-cut metallic company insignia, and minimalist linear overhead illumination.",
      materials: ["Handcrafted Chevron Timber", "Laser-Cut Brass Insignia", "Linear Overhead Pendant", "Recessed Baseboard Glow"],
      dimensions: "5.8m × 3.8m Wall Frame",
      aspectRatio: "landscape",
    },
    {
      id: "ch6_foyer",
      chamberId: "corporate_lobby",
      title: "The Executive Waiting Foyer & Guest Lounge",
      project: "BKC Commercial Hub",
      location: "Mumbai, Maharashtra",
      category: "Corporate Waiting Lounge",
      image: "/assets/exhibition/ch6_foyer.jpg",
      description:
        "Sophisticated corporate guest lounge featuring a tailored oatmeal leather sofa, organic sculptural marble cocktail tables, contemporary brass accents, and fluted acoustic wall transitions.",
      materials: ["Oatmeal Top-Grain Leather", "Organic Marble Coffee Table", "Acoustic Wall Paneling", "Architectural Track Spotlights"],
      dimensions: "5.8m × 3.8m Wall Frame",
      aspectRatio: "landscape",
    },
    {
      id: "ch6_lobby",
      chamberId: "corporate_lobby",
      title: "The Monumental Commercial Entrance Lobby",
      project: "BKC Commercial Hub",
      location: "Mumbai, Maharashtra",
      category: "Commercial Headquarters Foyer",
      image: "/assets/exhibition/ch6_lobby.jpg",
      description:
        "Panoramic wide-angle perspective of the corporate entrance lobby, seamlessly integrating reception greeting, visitor lounge hospitality, and executive meeting room access.",
      materials: ["Continuous Italian Marble", "Frameless Glass Partitions", "Aubergine Fluted Accent Walls", "Recessed Linear Lighting"],
      dimensions: "5.8m × 3.8m Wall Frame",
      aspectRatio: "landscape",
    },
    {
      id: "ch6_workstation",
      chamberId: "corporate_lobby",
      title: "The Global Operations Workstation Suite",
      project: "BKC Commercial Hub",
      location: "Mumbai, Maharashtra",
      category: "Executive Workstation Suite",
      image: "/assets/exhibition/ch6_workstation.jpg",
      description:
        "A high-performance executive suite with custom granite conference desks, ergonomic mesh seating, a graphic world map feature wall, and integrated ceiling diffusers.",
      materials: ["Honed Granite Desktops", "Ergonomic Mesh Executive Chairs", "World Map Typography Wall", "Modular Cable Management"],
      dimensions: "5.8m × 3.8m Wall Frame",
      aspectRatio: "landscape",
    },
  ],
};
